#! /bin/bash

# this script is more towards when the network settings is bridge,
# however I think it works in other settings as well.

# default user and password to the vm
vmuser="vm_user"

# --- start of util functions

# $1 is the vm name
getvmip() {
  vmname=$1
  vmip "$vmname" # see vmip subdirectory
  while [ $? -ne 0 ]; do
    sleep 5
    vmip "$vmname"
  done
}

# make sure connection to vm is established and valid ip is retruned
establish_ssh() {
  vmname=$1
  # try first the nice way that waits until ip is assigned
  ip=$(getvmip "$vmname")
  ssh -i ~/.ssh/vm_rsa "$vmuser@$ip" -- ls &>/dev/null
  while [ $? -ne 0 ]; do
    # try the hard way if the assigned ip is invalid
    ip=$(vmip "$vmname" --purge)
    ssh -i ~/.ssh/vm_rsa "$vmuser@$ip" -- ls &>/dev/null
  done
}

# -- start of case functions
create_fn() {
  next=$(($(vboxmanage list vms | sort | tail -n 1 | cut -d " " -f1 | cut -d "\"" -f2 | cut -d "_" -f2) + 1))
  vmname="vm_$(printf %02d $next)"
  vmbasedir="$HOME/.vms"
  imagename=$2

  mkdir -p "$vmbasedir"
  vboxmanage import "$HOME/.vms/boxes/${imagename}.ova" --vsys 0 --vmname "$vmname" --basefolder "$vmbasedir" --cpus 1 --memory 1024 >>"$vmbasedir/log.out"
  echo "vm created: $vmname"
  echo "$imagename" >>"$vmbasedir/$vmname/image"

  if [ "$#" -gt 2 ]; then
    script=$3
    rscript=$(basename "$script")

    echo "provisioning $vmname..."

    vboxmanage startvm "$vmname" --type headless >"$vmbasedir/log.out"

    establish_ssh "$vmname"
    ip=$(getvmip "$vmname")
    scp -i ~/.ssh/vm_rsa "$script" "$vmuser@$ip:/tmp/$rscript" >"$vmbasedir/log.out"
    ssh -i ~/.ssh/vm_rsa "$vmuser@$ip" -- chmod +x "/tmp/$rscript"
    ssh -i ~/.ssh/vm_rsa "$vmuser@$ip" -- "/tmp/$rscript"
  fi
}

rm_fn() {
  # accept multiple vms names
  for vmname in "${@:2}"; do
    echo "deleting $vmname ..."
    vboxmanage controlvm "$vmname" poweroff
    VBoxManage unregistervm "$vmname" --delete
    vmbasedir="$HOME/.vms"
    rm -rf "$vmbasedir/$vmname"
  done
}

start_fn() {
  # accept multiple vms names
  for vmname in "${@:2}"; do
    echo "starting $vmname ..."
    vboxmanage startvm "$vmname" --type headless
  done
}

stop_fn() {
  # accept multiple vms names
  for vmname in "${@:2}"; do
    echo "stoping $vmname ..."
    vboxmanage controlvm "$vmname" poweroff
  done
}

print_vms() {
  arr=$1
  printf "VM NAME\t\tIMAGE\t\t\tCPU\t\tMEM\t\tTAGS\n"
  if [ ${arr} ]; then
    for element in "${arr[@]}"; do
      spec=($(VBoxManage showvminfo ${element} --machinereadable | grep -E "memory=|cpus=" | cut -d "=" -f2))
      printf "%s\t\t$(cat ~/.vms/${element}/image)\t\t%s\t\t%s MB\t\t%s\n" ${element} ${spec[1]} ${spec[0]} \
        "$(echo $(cat ~/.vms/${element}/tags 2>/dev/null))"
    done
  fi
}

# ---- start of case statement
case $1 in
ls) # vm ls
  arr=($(vboxmanage list vms | cut -d " " -f1 | cut -d "\"" -f2))
  print_vms $arr
  ;;
ps) # vm ps
  arr=($(vboxmanage list runningvms | cut -d " " -f1 | cut -d "\"" -f2))
  print_vms $arr
  ;;
create)
  if [ $# -lt 2 ]; then
    printf "Usage: vm create <image> [/path/to/provision_script.sh]
\nWhere:
<image> = <distro name>/<distro version>
\nExamples:
$ vm create ubuntu/bionic
\nUse the sub command \"images\" to list all vm images avaiable
"
    exit 2
  fi
  create_fn "$@"
  ;;
rm)
  if [ $# -eq 1 ]; then
    printf "Usage: vm rm <vmname1> [,vmname2, ...]
\nExamples:
$ vm rm vm_01
"
    exit 2
  fi

  rm_fn "$@"
  ;;
start)
  if [ $# -eq 1 ]; then
    printf "Usage: vm start <vmname1> [,vmname2, ...]
\nExamples:
$ vm start vm_01
"
    exit 2
  fi

  start_fn "$@"
  ;;
stop)
  if [ $# -eq 1 ]; then
    printf "Usage: vm stop <vmname1> [,vmname2, ...]
\nExamples:
$ vm stop vm_01
"
    exit 2
  fi

  stop_fn "$@"
  ;;
ssh)
  if [ $# -lt 2 ]; then
    printf "Usage: vm ssh <vmname> [-- remote commands]
\nExamples:
$ vm ssh vm_01
\n$ vm ssh vm_01 -- cat /etc/passwd
"
    exit 2
  fi

  establish_ssh "$2"

  ip=$(getvmip "$2")
  ssh -i ~/.ssh/vm_rsa "$vmuser@$ip" "${@:3}"
  ;;
port)
  if [ $# -lt 3 ]; then
    printf "Usage: vm port <vmname> <vm port>[:local port] [<vm port>[:local port]]
\nExamples:
# forward vm port 4040 to local port 4040
$ vm port vm_01 4040
\n# forward vm port 4040 to local port 40040
$ vm port vm_01 4040:40040
\n# forward vm port 4040 to local port 40040 and port 8080 to 8080
$ vm port vm_01 4040:40040 8080
\n# forward vm port 4040 to local port 40040 and ports in range (8080 to 8088) to range(8080 to 8088)
$ vm port vm_01 4040:40040 8080-8088
\n# forward vm port 4040 to local port 40040 and ports in range (8080 to 8088) to range(9080 to 9088)
$ vm port vm_01 4040:40040 8080-8088:9080-9088
"
    exit 2
  fi

  vm_name="$2"
  ip=$(getvmip "$vm_name")
  ports="${*:3}"
  establish_ssh "$vm_name"

  printf "\nConnected. Press CTRL+C anytime to stop\n"
  ssh -i ~/.ssh/vm_rsa $(vmports $ports) "$vmuser@$ip" -N
  ;;
cp)
  if [ $# -lt 3 ]; then
    printf "Usage: vm cp <vmname> <local file>
\nCopy local files to home directory the vm
\nExamples:
# copy file.txt from host to user's home directory inside the vm
$ vm cp vm_01 file.txt
"
    exit 2
  fi

  vm_name="$2"
  local_file="$3"
  ip=$(getvmip "$vm_name")

  establish_ssh "$vm_name"

  scp -i ~/.ssh/vm_rsa $local_file $vmuser@$ip:/home/$vmuser/$local_file
  ;;
images)
  imagelist
  ;;
ip)
  if [ $# -lt 2 ]; then
    printf "Usage: vm ip <vmname> [--purge]
\nExamples:
$ vm ip vm_01
\n#to purge the IP cache:
$ vm ip vm_01 --purge
"
    exit 2
  fi

  vm_name="$2"
  vmip $vm_name "$3"
  ;;
tag) # very basic impl that does not prevent duplicates and without the ability to untag (go modify the file directly when needed)
  if [ $# -lt 3 ]; then
    printf "Usage: vm tag <vmname> <tag>
\nExamples:
$ vm tag vm_01 my_k8s
"
    exit 2
  fi

  vmname="$2"
  tag="$3"
  vmbasedir="$HOME/.vms"
  echo "$tag" >>"$vmbasedir/$vmname/tags"
  ;;
*)
  printf "Usage: vm <command> [options]
Create, control and connect to VirtualBox VM instances.

Available commands:

    Listing:
      ls        List created VMs
      ps        List running VMs
      images    List VM images
      ip        Show IP address for a running VM

    VM basic:
      create    Create a VM from VM image
      tag       Put a tag on a VM
      start     Start one or more VMs
      stop      Stop one or more VMs
      ssh       ssh into a running VM
      rm        Remove one or more VMs

  Host operations:
      port      Port forward from VM to host
      cp        Copy files from host to VM
"
  exit 2
  ;;
esac
